version: '3'
services:
  server:
    container_name: software-house-task-1
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 3000:3000
